Update trigger-gam-with-gh-cli.yaml

diff --git a/.github/workflows/trigger-gam-with-gh-cli.yaml b/.github/workflows/trigger-gam-with-gh-cli.yaml
--- a/.github/workflows/trigger-gam-with-gh-cli.yaml
+++ b/.github/workflows/trigger-gam-with-gh-cli.yaml
@@ -70,21 +70,21 @@ jobs:
         # Access the workflow details from the environment
         workflow_details="${{ env.workflow_details }}"
     
-    # Ensure the workflow details are properly quoted and accessible
-    echo "Workflow details: $workflow_details"
-    
-    # Extract the first object from the JSON array and get the databaseId
-    database_id=$(echo "$workflow_details" | jq '.[0].databaseId')
-    
-    # Check if we got a valid databaseId
-    if [ -z "$database_id" ]; then
-      echo "Error: databaseId not found in workflow details."
-      exit 1
-    fi
-    
-    # Log the workflow databaseId and initiate watching
-    echo "Watching workflow with ID: $database_id"
-    gh run watch --repo red-hat-data-services/gam-poc "$database_id"
+        # Ensure the workflow details are properly quoted and accessible
+        echo "Workflow details: $workflow_details"
+        
+        # Extract the first object from the JSON array and get the databaseId
+        database_id=$(echo "$workflow_details" | jq '.[0].databaseId')
+        
+        # Check if we got a valid databaseId
+        if [ -z "$database_id" ]; then
+          echo "Error: databaseId not found in workflow details."
+          exit 1
+        fi
+        
+        # Log the workflow databaseId and initiate watching
+        echo "Watching workflow with ID: $database_id"
+        gh run watch --repo red-hat-data-services/gam-poc "$database_id"
 
         
     
